#!/usr/bin/env python3
import sys
import time
import glob
import serial

def check(port, baudrate):
    ser = serial.Serial(
            port = port,
            baudrate = baudrate,
            timeout = 3)
    ser.isOpen()
    cmd = "*idn?\n"
    ser.write(cmd.encode())
    time.sleep(0.15)
    response = ser.read_all().decode("utf-8")[:-1]
    print (f'{port}: {response}')
    
def main():
    try:
        ports = sys.argv[1]
        if len(ports.split('/')) == 1:
            ports = '/dev/ttyUSB' + ports
        ports = [ports]
    except IndexError:
        ports = glob.glob('/dev/ttyUSB*')
    
    ports.sort()
    baudrate = 9600
    for port in ports: 
        try:
            check(port, baudrate)
        except serial.serialutil.SerialException:
            print (f'Invalid port {port}')
        

if __name__=="__main__":
    main()
