#!/usr/bin/env python3

import sys
import time
import serial

def check(port, baudrate):
    ser = serial.Serial(
            port = port,
            baudrate = baudrate,
            timeout = 3)
    ser.isOpen()
    cmd = "*idn?\n"
    ser.write(cmd.encode())
    time.sleep(0.15)
    response = ser.read_all().decode("utf-8")[:-1]
    print (response)
    
def main():
    port = sys.argv[1]
    baudrate = 9600
    try:
        check(port, baudrate)
    except serial.serialutil.SerialException:
        print (f'Invalid port {port}')

if __name__=="__main__":
    main()
